set -l p4_client_commands add aliases annotate attribute branch branches change changelist changelists changes clean client clients copy counter counters cstat delete depot depots describe diff diff2 dirs edit filelog files fix fixes flush fstat grep group groups have ignores info integrate integrated interchanges istat job jobs key keys label labels labelsync list lock logger login login2 logout merge move opened passwd populate print protect protects prune rec reconcile rename reopen repo repos reshelve resolve resolved revert review reviews set shelve sizes status stream streams submit switch sync tag tickets trust undo unlock unshelve update user users where workspace workspaces
complete -c p4 -n "__fish_use_subcommand" -f -a help -d "Print the requested help message"
complete -c p4 -n "__fish_seen_subcommand_from help" -a "$p4_client_commands"
complete -c p4 -n "not __fish_contains_opt help; and __fish_seen_subcommand_from $p4_client_commands" -l explain -d "display additional information about the flags"
complete -f -c p4 -n "__fish_use_subcommand" -a depot -d "Create or edit a depot specification"
complete -f -c p4 -n "__fish_use_subcommand" -a users -d "Display list of known users"
complete -f -c p4 -n "__fish_use_subcommand" -a aliases -d "Display the content of the P4ALIASES file"
complete -f -c p4 -n "__fish_use_subcommand" -a flush -d "Fake a 'p4 sync' by not moving files"
complete -f -c p4 -n "__fish_use_subcommand" -a changelist -d "Create or edit a changelist description"
complete -f -c p4 -n "__fish_use_subcommand" -a client -d "Create or edit a client specification and its view"
complete -f -c p4 -n "__fish_use_subcommand" -a branch -d "Create or edit a branch specification"
complete -f -c p4 -n "__fish_use_subcommand" -a counter -d "Display, set, or delete a counter"
complete -f -c p4 -n "__fish_use_subcommand" -a set -d "Set variables in the registry (Windows only)"
complete -f -c p4 -n "__fish_use_subcommand" -a rename -d "Moves files from one location to another"
complete -f -c p4 -n "__fish_use_subcommand" -a logout -d "Logout of Perforce by removing or invalidating a ticket"
complete -f -c p4 -n "__fish_use_subcommand" -a login2 -d "Perform a multi factor authentication"
complete -f -c p4 -n "__fish_use_subcommand" -a fixes -d "List what changelists fix what job"
complete -f -c p4 -n "__fish_use_subcommand" -a tickets -d "Display list of session tickets for this user"
complete -f -c p4 -n "__fish_use_subcommand" -a fstat -d "Dump file info"
complete -f -c p4 -n "__fish_use_subcommand" -a list -d "Create an in-memory (label) list of depot files"
complete -f -c p4 -n "__fish_use_subcommand" -a reviews -d "Show what users are subscribed to review files"
complete -f -c p4 -n "__fish_use_subcommand" -a grep -d "Print lines from text files matching a pattern"
complete -f -c p4 -n "__fish_use_subcommand" -a clean -d "Delete or refresh local files to match depot state"
complete -f -c p4 -n "__fish_use_subcommand" -a switch -d "Switch to a different stream, or create a new stream."
complete -f -c p4 -n "__fish_use_subcommand" -a annotate -d "Print file lines along with their revisions"
complete -f -c p4 -n "__fish_use_subcommand" -a jobs -d "Display list of jobs"
complete -f -c p4 -n "__fish_use_subcommand" -a streams -d "Display list of streams"
complete -f -c p4 -n "__fish_use_subcommand" -a ignores -d "List P4IGNORE mappings"
complete -f -c p4 -n "__fish_use_subcommand" -a integrate -d "Schedule integration from one file to another"
complete -f -c p4 -n "__fish_use_subcommand" -a info -d "Print out client/server information"
complete -f -c p4 -n "__fish_use_subcommand" -a passwd -d "Set the user's password on the server (and Windows client)"
complete -f -c p4 -n "__fish_use_subcommand" -a print -d "Retrieve a depot file to the standard output"
complete -f -c p4 -n "__fish_use_subcommand" -a sizes -d "Display size information for files in the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a change -d "Create or edit a changelist description"
complete -f -c p4 -n "__fish_use_subcommand" -a revert -d "Discard changes from an opened file"
complete -f -c p4 -n "__fish_use_subcommand" -a labels -d "Display list of labels"
complete -f -c p4 -n "__fish_use_subcommand" -a attribute -d "Set per-revision attributes on revisions"
complete -f -c p4 -n "__fish_use_subcommand" -a workspaces -d "Display list of known clients"
complete -f -c p4 -n "__fish_use_subcommand" -a changes -d "Display list of pending and submitted changelists"
complete -f -c p4 -n "__fish_use_subcommand" -a istat -d "Show integrations needed for a stream"
complete -f -c p4 -n "__fish_use_subcommand" -a user -d "Create or edit a user specification"
complete -f -c p4 -n "__fish_use_subcommand" -a reshelve -d "Copy shelved files to a new or existing shelf"
complete -f -c p4 -n "__fish_use_subcommand" -a add -d "Open a new file to add it to the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a repo -d "Create, edit or delete a repo specification"
complete -f -c p4 -n "__fish_use_subcommand" -a delete -d "Open an existing file to delete it from the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a rec -d "Reconcile client to offline workspace changes"
complete -f -c p4 -n "__fish_use_subcommand" -a trust -d "Establish trust of an SSL connection"
complete -f -c p4 -n "__fish_use_subcommand" -a fix -d "Mark jobs as being fixed by named changelists"
complete -f -c p4 -n "__fish_use_subcommand" -a reopen -d "Change the type or changelist number of an opened file"
complete -f -c p4 -n "__fish_use_subcommand" -a counters -d "Display list of known counters"
complete -f -c p4 -n "__fish_use_subcommand" -a labelsync -d "Synchronize label with the current client contents"
complete -f -c p4 -n "__fish_use_subcommand" -a filelog -d "List revision history of files"
complete -f -c p4 -n "__fish_use_subcommand" -a tag -d "Tag files with a label"
complete -f -c p4 -n "__fish_use_subcommand" -a sync -d "Synchronize the client with its view of the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a resolved -d "Show files that have been merged but not submitted"
complete -f -c p4 -n "__fish_use_subcommand" -a files -d "List files in the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a unlock -d "Release a locked file but leave it open"
complete -f -c p4 -n "__fish_use_subcommand" -a move -d "Moves files from one location to another"
complete -f -c p4 -n "__fish_use_subcommand" -a submit -d "Submit open files to the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a dirs -d "List subdirectories of a given depot directory"
complete -f -c p4 -n "__fish_use_subcommand" -a interchanges -d "Report changes that have not yet been integrated"
complete -f -c p4 -n "__fish_use_subcommand" -a merge -d "Schedule merge (integration) from one file to another"
complete -f -c p4 -n "__fish_use_subcommand" -a have -d "List revisions last synced"
complete -f -c p4 -n "__fish_use_subcommand" -a resolve -d "Merge open files with other revisions or files"
complete -f -c p4 -n "__fish_use_subcommand" -a shelve -d "Store files from a pending changelist into the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a stream -d "Create or edit a stream specification"
complete -f -c p4 -n "__fish_use_subcommand" -a where -d "Show how file names map through the client view"
complete -f -c p4 -n "__fish_use_subcommand" -a groups -d "List groups (of users)"
complete -f -c p4 -n "__fish_use_subcommand" -a edit -d "Open an existing file for edit"
complete -f -c p4 -n "__fish_use_subcommand" -a branches -d "Display list of branches"
complete -f -c p4 -n "__fish_use_subcommand" -a label -d "Create or edit a label specification and its view"
complete -f -c p4 -n "__fish_use_subcommand" -a logger -d "Report what jobs and changelists have changed"
complete -f -c p4 -n "__fish_use_subcommand" -a cstat -d "Dump change/sync status for current client"
complete -f -c p4 -n "__fish_use_subcommand" -a changelists -d "Display list of pending and submitted changelists"
complete -f -c p4 -n "__fish_use_subcommand" -a update -d "Update the client with its view of the depot"
complete -f -c p4 -n "__fish_use_subcommand" -a review -d "List and track changelists (for the review daemon)"
complete -f -c p4 -n "__fish_use_subcommand" -a protect -d "Modify protections in the server namespace"
complete -f -c p4 -n "__fish_use_subcommand" -a undo -d "Undo a range of revisions"
complete -f -c p4 -n "__fish_use_subcommand" -a opened -d "Display list of files opened for pending changelist"
complete -f -c p4 -n "__fish_use_subcommand" -a workspace -d "Create or edit a client specification and its view"
complete -f -c p4 -n "__fish_use_subcommand" -a keys -d "Display list of known keys and their values"
complete -f -c p4 -n "__fish_use_subcommand" -a key -d "Display, set, or delete a key/value pair"
complete -f -c p4 -n "__fish_use_subcommand" -a integrated -d "Show integrations that have been submitted"
complete -f -c p4 -n "__fish_use_subcommand" -a copy -d "Schedule copy of latest rev from one file to another"
complete -f -c p4 -n "__fish_use_subcommand" -a login -d "Login to Perforce by obtaining a session ticket"
complete -f -c p4 -n "__fish_use_subcommand" -a status -d "Preview reconcile of client to offline workspace changes"
complete -f -c p4 -n "__fish_use_subcommand" -a job -d "Create or edit a job (defect) specification"
complete -f -c p4 -n "__fish_use_subcommand" -a depots -d "Display list of depots"
complete -f -c p4 -n "__fish_use_subcommand" -a diff -d "Display diff of client file with depot file"
complete -f -c p4 -n "__fish_use_subcommand" -a repos -d "Display a list of repos (depots of type graph)"
complete -f -c p4 -n "__fish_use_subcommand" -a clients -d "Display list of known clients"
complete -f -c p4 -n "__fish_use_subcommand" -a prune -d "Remove unmodified branched files from a stream"
complete -f -c p4 -n "__fish_use_subcommand" -a reconcile -d "Reconcile client to offline workspace changes"
complete -f -c p4 -n "__fish_use_subcommand" -a group -d "Change members of a user group"
complete -f -c p4 -n "__fish_use_subcommand" -a lock -d "Lock an opened file against changelist submission"
complete -f -c p4 -n "__fish_use_subcommand" -a populate -d "Populate a branch or stream with files"
complete -f -c p4 -n "__fish_use_subcommand" -a protects -d "Display protections in place for a given user/path"
complete -f -c p4 -n "__fish_use_subcommand" -a describe -d "Display a changelist description"
complete -f -c p4 -n "__fish_use_subcommand" -a diff2 -d "Display diff of two depot files"
complete -f -c p4 -n "__fish_use_subcommand" -a unshelve -d "Restore shelved files from a pending changelist"
set -l p4c_help networkaddress administration simple usage jobview configurables commands command revisions streamintro replication views environment legal filetypes dvcs charset

complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a networkaddress -d 'help on network address syntax'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a administration -d 'help on specialized administration topics'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a simple -d 'list most common commands'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a usage -d 'generic command line arguments'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a jobview -d 'help on jobview syntax'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a configurables -d 'list server configuration variables'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a commands -d 'list all standard commands'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a command -d 'help on a specific command'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a revisions -d 'help on specifying file revisions'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a streamintro -d 'introduction to streams'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a replication -d 'help on specialized replication topics'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a views -d 'help on view syntax'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a environment -d 'list environment and registry variables'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a legal -d 'legal and license information'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a filetypes -d 'list supported file types'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a dvcs -d 'help on decentralized Perforce configurations'
complete -f -c p4 -n "__fish_seen_subcommand_from help; and not __fish_contains_opt $p4c_help" -a charset -d 'help on character set translation'
